language: node_js
node_js:
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
    - master

cache: yarn

script:
  - yarn lint
  - yarn test

notifications:
  slack:
    secure: h5xEk3F/x0Kpj6d9EuUl9+uHfDUYcxkZhcUtk6SAKy6Mi47XxAYOYHeknQIT1wfiiqWOzATii6Cw2yFVT+KQmQSbg2goXxWI1kiWMJYExbfcgqQnnaaEtIkpD1RZZ6uCCgxJ5LRWzCmq4dVSj8zd8I0Taod9v6fX36uToc6IPo6zyLKqP4YIrUOghzvhrUU4mIe+4nlNnbbpVQ8wRO6VqYyMZNxgunkSEj5UIVnnKQ1dr1VkVuXP982gK4N6QIIsNiU0voIT/+NjnfXBz7ARZ7mscK8pgHqHv3p5Du2C8iFLpRN9R/+lcODfOy+MKwwILd8L631VNhlE3sIr47Nk8Nxo2B363hqvPWSkuMLjd0RTKpqd9/7bxn1zrWvssoXWOPJ/r2+EV59I1WKq7p/eZndzyGdro3f6cHmcjr0w8L4s+CKm074VU+pKbfzQYD6xEChDL7HMmfUW8R1b7Agwy+60dhjgbHiMBDBdl3xWZbq7BfkgV0BQm39AhPx3c5o1vXPw5oAWOhR3xrQ2TfK2EWvap8JjywBeqg27/KpCNLbzrJ69elo7tQOt/Up/aoWzW075fm8LMdR4ZsKelgd6iqvxPvJedmW5SorVV2cSbRVVe36GAnbMeEJU0Epv6ufMngYwqK90oQq4vvb1wu2oq+f5u+g8BHyNmcKbKtqRcVE=
