language: node_js
node_js:
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
    - master

cache: yarn

script:
  - yarn lint
  - yarn test

notifications:
  slack:
    secure: h5xEk3F/x0Kpj6d9EuUl9+uHfDUYcxkZhcUtk6SAKy6Mi47XxAYOYHeknQIT1wfiiqWOzATii6Cw2yFVT+KQmQSbg2goXxWI1kiWMJYExbfcgqQnnaaEtIkpD1RZZ6uCCgxJ5LRWzCmq4dVSj8zd8I0Taod9v6fX36uToc6IPo6zyLKqP4YIrUOghzvhrUU4mIe+4nlNnbbpVQ8wRO6VqYyMZNxgunkSEj5UIVnnKQ1dr1VkVuXP982gK4N6QIIsNiU0voIT/+NjnfXBz7ARZ7mscK8pgHqHv3p5Du2C8iFLpRN9R/+lcODfOy+MKwwILd8L631VNhlE3sIr47Nk8Nxo2B363hqvPWSkuMLjd0RTKpqd9/7bxn1zrWvssoXWOPJ/r2+EV59I1WKq7p/eZndzyGdro3f6cHmcjr0w8L4s+CKm074VU+pKbfzQYD6xEChDL7HMmfUW8R1b7Agwy+60dhjgbHiMBDBdl3xWZbq7BfkgV0BQm39AhPx3c5o1vXPw5oAWOhR3xrQ2TfK2EWvap8JjywBeqg27/KpCNLbzrJ69elo7tQOt/Up/aoWzW075fm8LMdR4ZsKelgd6iqvxPvJedmW5SorVV2cSbRVVe36GAnbMeEJU0Epv6ufMngYwqK90oQq4vvb1wu2oq+f5u+g8BHyNmcKbKtqRcVE=

deploy:
  provider: heroku
  api_key:
    secure: O38dx7K+VxaYhnKUaiA0yzpxIbusGtuCQTdRL7vNJBdzFmVRtcJ0ta9XwfPJJwSRdFGIle/YJItvvzE1TfwWznhze9rjptICj7idL89uTSQ/IhfZM2hVt4FZVnG8qWOObduOoZNlW9WXBCFzm5dc3ONGXLYpbuCg6EOeNkrUALew1DcFQdg8jIXYiyOc7DGV/RC816Gl+eT0GI7hXABrAzeZgKwYmjYLcQ4NuECgZPk71KkxaLwU0AUhhvucXgIjJYXDLCmH+1nmDWkInb5cj1A+AKA2mHnrZQ3v9JMjr/Yg+Kbd2FYeF/ZA1oj8ymZSQu3px/JwX5bq/FSxxTKksvxqfSihI+/0+JZlHaR1xjNqEMI1Dn01Sw1CemQ4B/bC/Zeeoe7bdfDPIDrnpo8oFuGbPbrgB8TJCOufa+dfbx6EKBeZiet17G2TlR4jm8Ktm0zyg1UYppOIAFXR/+LoSVsFhI4502DZCfVoumaZJp2N3ZbMwootYtKvLEelt7RIQkO5hKiNhl9XaJMQrQsyD1TMXWNNNUlXFOnKi6fRPZ9x+Fn3lkHs46u5xDvoY2ALpYFdjwdxDN/x1K0Nnsuvtj/Wa5/vao7RAvh/gzA/ugWhlOv9Pt5CbFCSyVNu1uQKB9w++7yVqp6Y5sWb4tRTsVhjHmKGnkcK8gKyaplTno0=
  app: smat-dev
