language: node_js
node_js:
  - node

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.12.3
  - export PATH="$HOME/.yarn/bin:$PATH"

branches:
  only:
    - master

cache: yarn

script:
  - yarn lint
  - yarn test

notifications:
  slack:
    secure: h5xEk3F/x0Kpj6d9EuUl9+uHfDUYcxkZhcUtk6SAKy6Mi47XxAYOYHeknQIT1wfiiqWOzATii6Cw2yFVT+KQmQSbg2goXxWI1kiWMJYExbfcgqQnnaaEtIkpD1RZZ6uCCgxJ5LRWzCmq4dVSj8zd8I0Taod9v6fX36uToc6IPo6zyLKqP4YIrUOghzvhrUU4mIe+4nlNnbbpVQ8wRO6VqYyMZNxgunkSEj5UIVnnKQ1dr1VkVuXP982gK4N6QIIsNiU0voIT/+NjnfXBz7ARZ7mscK8pgHqHv3p5Du2C8iFLpRN9R/+lcODfOy+MKwwILd8L631VNhlE3sIr47Nk8Nxo2B363hqvPWSkuMLjd0RTKpqd9/7bxn1zrWvssoXWOPJ/r2+EV59I1WKq7p/eZndzyGdro3f6cHmcjr0w8L4s+CKm074VU+pKbfzQYD6xEChDL7HMmfUW8R1b7Agwy+60dhjgbHiMBDBdl3xWZbq7BfkgV0BQm39AhPx3c5o1vXPw5oAWOhR3xrQ2TfK2EWvap8JjywBeqg27/KpCNLbzrJ69elo7tQOt/Up/aoWzW075fm8LMdR4ZsKelgd6iqvxPvJedmW5SorVV2cSbRVVe36GAnbMeEJU0Epv6ufMngYwqK90oQq4vvb1wu2oq+f5u+g8BHyNmcKbKtqRcVE=

deploy:
  provider: heroku
  api_key:
    secure: HAipWrzsny/dmfEdtJaWNSyYUx33ZLMhlut+YJGzAfogg2WNBXxQaCBFCjoNuzY7kdRjeVRCMiEF2P+XPT8a3anLonyqB01rDpcUWON0HbgfIqMZdB1I/hNfOyDQgErRXc5IKlsaJELB/KlS1ofEy3UhvM2IT9d41kVHgeqIhkp9+g9DqL4DaOFQdAG5vJ0GASjPhALZg/3mCr4XaYnJW2CngHLSKH67eXPYRHhs7a/DgF2+NgztRpvmTFTuUsFkPFUS56hGLhJQR75tLf+vctE0NXS70l73cQTWjtnD4iU2kKMW1iy4opltKxRdle65TN07PMLDP3fzv6EZwr4/8NSa3MTon199KzjOr5yBWwksI2gK6JW0Aw9PjXD1PLSk5hKcDAdluPz6nkNNsk1/vtFxMvDGeDfNM95zWPH3xIeJZs3+MzOGQ+c3MN5kuOS8pNRjBNiSVx9ni976w6dhXLa8MHBzRvJLggEGm73FiZfBrK1qZCBgC8NN6nqedyn3TyqAe+yNFSmUkT+ZKY42XYDD/HedU2Mmfq1BDe/002FuK+elwBLNDUDKqrgrz4sZxJ9zYG+hhtkAJuoqzb8s/fEQcd63/ZqYnMNmz8/fFQRh85nz9Z+oQzGGPXtRAVopv3nGdtCFG6oSmSpm4NH+O7aD4iRLpuhJiruWbFn4i58=
  app: smat-dev
